#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Sound:
    key: str
    phoneme: str | None = None
    stressed: bool = False


@dataclass(frozen=True)
class ConsonantData:
    group: int
    thud: int
    soft: int


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "lib" / "bel_lang_engine" / "data" / "sound_compatibility.tsv"

VOWELS = ["а", "о", "у", "і", "ы", "э"]
CONSONANTS: dict[str, ConsonantData] = {
    "б": ConsonantData(0, 0, 0),
    "б'": ConsonantData(0, 0, 1),
    "п": ConsonantData(0, 1, 0),
    "п'": ConsonantData(0, 1, 1),
    "в": ConsonantData(1, 0, 0),
    "в'": ConsonantData(1, 0, 1),
    "г": ConsonantData(2, 0, 0),
    "г'": ConsonantData(2, 0, 1),
    "х": ConsonantData(2, 1, 0),
    "х'": ConsonantData(2, 1, 1),
    "г*": ConsonantData(3, 0, 0),
    "г*'": ConsonantData(3, 0, 1),
    "к": ConsonantData(3, 1, 0),
    "к'": ConsonantData(3, 1, 1),
    "д": ConsonantData(4, 0, 0),
    "дз'": ConsonantData(4, 0, 1),
    "т": ConsonantData(4, 1, 0),
    "ц'": ConsonantData(4, 1, 1),
    "дз": ConsonantData(5, 0, 0),
    "ц": ConsonantData(5, 1, 0),
    "ж": ConsonantData(6, 0, 0),
    "ш": ConsonantData(6, 1, 0),
    "з": ConsonantData(7, 0, 0),
    "з'": ConsonantData(7, 0, 1),
    "с": ConsonantData(7, 1, 0),
    "с'": ConsonantData(7, 1, 1),
    "й": ConsonantData(8, 0, 1),
    "л": ConsonantData(9, 0, 0),
    "л'": ConsonantData(9, 0, 1),
    "м": ConsonantData(10, 0, 0),
    "м'": ConsonantData(10, 0, 1),
    "н": ConsonantData(11, 0, 0),
    "н'": ConsonantData(11, 0, 1),
    "р": ConsonantData(12, 0, 0),
    "ф": ConsonantData(13, 1, 0),
    "ф'": ConsonantData(13, 1, 1),
    "дж": ConsonantData(14, 0, 0),
    "ч": ConsonantData(14, 1, 0),
    "ў": ConsonantData(15, 0, 0),
}


def is_whistling(phoneme: str) -> bool:
    return phoneme in {"з", "з'", "с", "с'", "дз", "дз'", "ц", "ц'"}


def is_hissing(phoneme: str) -> bool:
    return phoneme in {"ж", "ш", "дж", "ч"}


def sound_keys() -> list[Sound]:
    sounds = [Sound("<empty>")]
    sounds += [Sound(vowel, vowel) for vowel in VOWELS]
    sounds += [Sound(f"_{vowel}_", vowel, True) for vowel in VOWELS]
    sounds += [Sound(consonant, consonant) for consonant in CONSONANTS]
    return sounds


def replace_cost(left: Sound, right: Sound) -> float:
    if left.phoneme is None and right.phoneme is None:
        return 0.0
    if left.phoneme is None or right.phoneme is None:
        return 1000.0

    left_is_vowel = left.phoneme in VOWELS
    right_is_vowel = right.phoneme in VOWELS
    left_is_consonant = left.phoneme in CONSONANTS
    right_is_consonant = right.phoneme in CONSONANTS

    if left_is_vowel and right_is_vowel:
        if left.phoneme == right.phoneme:
            return 0.0 if left.stressed == right.stressed else 20.0
        if {left.phoneme, right.phoneme} == {"і", "ы"}:
            return 0.0
        if left.stressed and right.stressed:
            return 10.0
        if left.stressed or right.stressed:
            return 30.0
        return 1.0

    if left_is_consonant and right_is_consonant:
        if left.phoneme == right.phoneme:
            return 0.0

        left_data = CONSONANTS[left.phoneme]
        right_data = CONSONANTS[right.phoneme]
        diff = (
            abs(left_data.thud - right_data.thud)
            + abs(left_data.soft - right_data.soft) * 2
        ) * 7.0

        if left_data.group == right_data.group:
            diff /= 2.0
        else:
            diff += 6.0

        if is_whistling(left.phoneme) and is_whistling(right.phoneme):
            diff /= 3.0
        if is_hissing(left.phoneme) and is_hissing(right.phoneme):
            diff /= 3.0
        return diff

    if left_is_consonant and right_is_vowel:
        left, right = right, left

    if left.phoneme in VOWELS and right.phoneme in CONSONANTS:
        if CONSONANTS[right.phoneme].thud == 0:
            return 30.0 if left.stressed else 15.0
        return 40.0 if left.stressed else 20.0

    return 1000.0


def format_cost(cost: float) -> str:
    return f"{cost:.12g}"


def main() -> None:
    output = DEFAULT_OUTPUT
    output.parent.mkdir(parents=True, exist_ok=True)

    sounds = sound_keys()
    with output.open("w", encoding="utf-8") as file:
        file.write("# Generated by scripts/generate_sound_compatibility.py\n")
        file.write("# left_sound\\tright_sound\\treplace_cost\n")
        for left in sounds:
            for right in sounds:
                file.write(
                    f"{left.key}\t{right.key}\t{format_cost(replace_cost(left, right))}\n"
                )


if __name__ == "__main__":
    main()
